language: python
python:
  - "2.7"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - pip install -r requirements.txt
  - pip install https://cdn.mysql.com/Downloads/Connector-Python/mysql-connector-python-2.1.2.tar.gz
script:
  - python runtests.py